name: node_manager CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        build_type: [Release]
        idf_version: [v5.1, v5.2]
        target: [esp32s3]
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: 'examples/simple'
          esp_idf_version: ${{ matrix.idf_version }}
          target: ${{ matrix.target }}
          
